#!/usr/bin/env python
'''

usage:  random-name --component=<list>... [--separator=<string>] [<count>]
        random-name help

  <count>               how many names to generate [default: 1]
  --component=<list>    a comma-separated list of namefiles to read from. Multiple component entries
                        are allowed, each corresponding to a part of the name. Globbing is supported
  --separator=<string>  a string of text to place between name components [default: -]

examples:

    random-name generate --component=path/to/namelist --component=path/to/namelist2 30
    random-name generate --component=first* --component=middle* 30

'''
import random, glob
from docopt import docopt
from subprocess import call

args = docopt(__doc__, version="random-name 0.1", help=True)
if args['help']:
    exit(call(['python','random-name','--help']))
else:
    if not args['<count>']:
        args['<count>'] = 1

    wordlists = []
    for i in range(len(args['--component'])):
        words = []
        entries = args['--component'][i].split(',')
        for entry in entries:
            files = glob.glob(entry)
            for fn in files:
                with open(fn) as f:
                    words.extend(f.read().splitlines())
        wordlists.append(words)

    for i in range(int(args['<count>'])):
        random_name = []
        for words in wordlists:
            random_name.append(random.choice(words))
        print(args['--separator'].join(random_name))

